services:
  - type: web
    name: anand-upscaler
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT"
